### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by Worgrick** [shedaniel/gravel-ores#2]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 5/31/20 8:04 PM
Description: Initializing game

net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'gravel-ores'
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193)
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:228)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:402)
	at net.minecraft.client.main.Main.main(Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.NoSuchMethodError: net.fabricmc.fabric.api.object.builder.v1.block.FabricMaterialBuilder.requiresTool()Lnet/fabricmc/fabric/api/object/builder/v1/block/FabricMaterialBuilder;
	at me.shedaniel.gravelores.GravelOres.<clinit>(GravelOres.java:49)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193)
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:228)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:402)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 20w22a
	Minecraft Version ID: 20w22a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1400925184 bytes (1336 MB) / 1711276032 bytes (1632 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		artifice: Artifice 0.6.1+20w19a
		fabric: Fabric API 0.11.1+build.350-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c0b
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.4+4a08d6b20b
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890b
		fabric-command-api-v1: Fabric Command API (v1) 1.0.3+da175ad60b
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308360b
		fabric-containers-v0: Fabric Containers (v0) 0.1.7+d249f7b60b
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.7+da175ad60b
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0b
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.1+6d41837a0b
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+1a47cd780b
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.12+63435d4b0b
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.2+4a08d6b20b
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.8+da175ad60b
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce990b
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60b
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b0b
		fabric-networking-v0: Fabric Networking (v0) 0.1.9+1a47cd780b
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.1+c6ab3e1b0b
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad60b
		fabric-particles-v1: fabric-particles-v1 0.1.3+4a08d6b20b
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.4+da175ad60b
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb80b
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.0+4a01746c0b
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600b
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0b
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+12a8474c0b
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900b
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.1+1aa9d4720b
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.0+da175ad60b
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.4+2fd224ca0b
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb80b
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.1+da175ad60b
		fabricloader: Fabric Loader 0.8.5+build.199
		godown: Go Down 0.2.0+20w07a
		gravel-ores: Gravel Ores 2.0.0-unstable
		minecraft: Minecraft 1.16-alpha.20.22.a
		water-erosion: Water Erosion 1.1.1
	Launched Version: fabric-loader-0.8.5+build.199-20w22a
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by shedaniel** [comment]
this is not updated to 20w22a yet
